version: '3'

services:
  api:
    image: node:16
    container_name: 'api_register'
    platform: linux/x86_64
    restart: 'always'
    tty: true
    stdin_open: true
    command: bash -c "npm install && npm run start:dev"
    working_dir: /app
    volumes:
      - './:/app'
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'db_pg'
    restart: always
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: user_register_db